const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const products=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/demo-products.json'),'utf8'));
const out=path.resolve(__dirname,'../dist/demo');
const base='https://kastor-product.pages.dev';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route=p=>`/demo/p/${p.id}`;
assert.equal(products.length,10);
assert.equal(new Set(products.map(p=>p.id)).size,10);
for(const p of products){assert.match(p.id,/^KST-DEMO-\d{4}$/);assert.ok(Object.keys(p.specs).length);if(p.replacement)assert.ok(products.some(q=>q.id===p.replacement));}
fs.mkdirSync(out,{recursive:true});
fs.mkdirSync(path.join(out,'images'),{recursive:true});
for(const p of products)fs.copyFileSync(path.join(__dirname,'../assets/demo',p.id+'.png'),path.join(out,'images',p.id+'.png'));
const css=`.demo-banner{padding:12px 18px;background:#fff1d6;color:#785315;border:1px solid #eddbb7;border-radius:6px;font-size:12px;line-height:1.6;margin-bottom:28px}.demo-title{margin-bottom:18px}.lead{color:#697160;line-height:1.7;font-size:14px;max-width:620px}.catalog{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:28px}.product-card{display:block;border:1px solid #dce0d7;background:white;border-radius:8px;padding:24px;transition:border-color .15s}.product-card:hover{border-color:#667354}.product-card:focus-visible,a:focus-visible{outline:3px solid #697b50;outline-offset:4px}.card-id{font-size:11px;letter-spacing:1px;color:#75816b}.product-card h2{font-size:20px;line-height:1.35;margin:13px 0;letter-spacing:-.4px}.card-meta{font-size:12px;color:#717966;line-height:1.7}.card-action{display:block;margin:22px 0 0;font-size:12px;color:#52603f}.back{display:inline-block;font-size:12px;color:#61704f;margin-bottom:28px}.qr-panel{display:flex;align-items:center;gap:26px;padding:25px;border:1px solid #dce0d7;background:white;border-radius:8px;margin-top:28px}.qr-panel img{width:160px;height:160px;flex-shrink:0}.qr-panel h2{font-size:17px}.qr-panel p{font-size:12px;line-height:1.7;color:#697160;overflow-wrap:anywhere}.button{display:inline-block;padding:11px 15px;background:#566449;border-radius:5px;color:white;font-size:12px;margin-top:8px}.retired{padding:19px;background:#f4ece4;border-left:3px solid #a57d53;margin:0 0 25px;font-size:13px;line-height:1.8}.retired a{text-decoration:underline}.explain{border-top:1px solid #dce0d7;padding-top:24px;margin-top:35px;font-size:13px;line-height:1.8;color:#697160}.demo-id{margin:18px 0 0;font-size:12px;color:#697160}.status{font-size:10px;display:inline-block;background:#f2e8db;color:#825e32;padding:4px 7px;border-radius:3px;margin-left:8px}@media(max-width:600px){.catalog{grid-template-columns:1fr}.qr-panel{flex-direction:column;align-items:flex-start;padding:20px}.qr-panel img{align-self:center}.product-card{padding:21px}}`;
fs.writeFileSync(path.join(out,'demo.css'),css+`\n.card-photo{width:100%;height:auto;aspect-ratio:1;object-fit:contain;border-radius:5px;margin:0 0 18px;background:#eeeae3}.demo-photo{margin:0 0 28px}.demo-photo img{display:block;width:100%;height:auto;max-height:580px;object-fit:contain;background:#eeeae3;border-radius:8px}.demo-photo figcaption{font-size:11px;color:#7d715f;line-height:1.6;margin-top:9px}`);
function shell(title,body){const t=esc(title+' — Demo Kastor');return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${t}</title><meta name="description" content="Demo 10 produk dummy. Bukan spesifikasi resmi Kastor."><meta property="og:title" content="${t}"><meta property="og:description" content="DATA DUMMY — bukan spesifikasi resmi Kastor."><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${t}"><meta name="twitter:description" content="DATA DUMMY — bukan spesifikasi resmi Kastor."><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/demo/demo.css"></head><body><div class="site"><header><a class="wordmark" href="/demo">KASTOR<span>®</span></a><span class="header-note">PRODUCT DEMO</span></header><main><div class="demo-banner"><strong>DATA DUMMY</strong> · Foto ilustrasi AI, nama, seri, dan seluruh spesifikasi di halaman demo ini hanya contoh. Bukan acuan pembelian atau pemasangan.</div>${body}</main><footer><span>KASTOR / DEMO</span><span>10 produk · 1 template · 10 QR</span></footer></div></body></html>`;}
const cards=products.map(p=>`<a class="product-card" href="${route(p)}"><img class="card-photo" src="/demo/images/${p.id}.png" alt="Ilustrasi AI: ${esc(p.name)}" width="1254" height="1254" loading="lazy"><span class="card-id">${p.id}</span>${p.status==='discontinued'?'<span class="status">Discontinued</span>':''}<h2>${esc(p.name)}</h2><div class="card-meta">${esc(p.series)} Series · ${Object.keys(p.specs).length} spesifikasi<br>${esc(p.specs.Type)}</div><p class="card-action">Lihat spesifikasi & QR →</p></a>`).join('');
fs.writeFileSync(path.join(out,'index.html'),shell('Katalog 10 Produk Dummy',`<div class="eyebrow"><span class="dot"></span> KATALOG PERCONTOHAN</div><section class="intro"><h1 class="demo-title">10 produk.<br>Satu sistem yang rapi.</h1><p class="lead">Setiap produk punya data sendiri, ID tetap, dan QR unik. Nama serta spesifikasi dapat diperbarui tanpa mengubah alamat QR.</p><a class="button" href="/demo/qr-demo.zip" download>Unduh semua 10 QR</a></section><section class="catalog" aria-label="10 produk dummy">${cards}</section><section class="explain"><strong>Coba dua contoh berbeda:</strong> Iris menampilkan ukuran dan cutout; Linea menampilkan daya, CCT, dan beam angle. Field yang tidak diisi tidak ditampilkan.<br><br><strong>Produk dihentikan:</strong> KST-DEMO-0009 tetap dapat dibuka dan menunjuk ke produk penggantinya. ID lama tidak dipakai ulang.<br><br>ID demo dipisahkan dari ID produk asli. Halaman Iris asli dan QR-nya tidak berubah.</section><a class="back" href="/">← Kembali ke produk Iris asli</a>`));
for(const p of products){
const rows=Object.entries(p.specs).filter(([,v])=>v!==null&&v!=='').map(([k,v],i)=>`<div class="spec-row"><dt><span class="number">${String(i+1).padStart(2,'0')}</span>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');
const retired=p.status==='discontinued'?`<aside class="retired"><strong>Contoh produk discontinued</strong><br>ID dan QR lama tetap berfungsi. Produk pengganti: <a href="/demo/p/${p.replacement}">${esc(products.find(q=>q.id===p.replacement).name)} (${p.replacement})</a>.</aside>`:'';
const html=shell(p.name,`<a class="back" href="/demo">← Semua produk demo</a><div class="eyebrow"><span class="dot"></span>${esc(p.series)} · CONTOH PRODUK</div><section class="intro"><p class="label">Product Name</p><h1>${esc(p.name)}</h1><p class="demo-id">Product ID: <strong>${p.id}</strong> · ID tetap</p></section>${retired}<figure class="demo-photo"><img src="/demo/images/${p.id}.png" alt="Ilustrasi AI: ${esc(p.name)}" width="1254" height="1254" fetchpriority="high"><figcaption>Ilustrasi buatan AI untuk demo — bukan foto produk resmi Kastor.</figcaption></figure><section class="specifications"><div class="section-title"><h2>Spesifikasi contoh</h2><span>DATA DUMMY</span></div><dl>${rows}</dl></section><section class="qr-panel"><img src="/demo/qr/${p.id}.png" alt="QR demo ${p.id}" width="160" height="160"><div><h2>QR khusus produk ini</h2><p>${base}${route(p)}</p><a class="button" href="/demo/qr/${p.id}.png" download="${p.id}.png">Unduh QR PNG</a><p>QR ini untuk pengujian, bukan label produk resmi.</p></div></section><p class="explain">Nama dan spesifikasi boleh direvisi. ID <strong>${p.id}</strong> dan alamat halaman dipertahankan agar QR tetap berlaku. Perubahan belum otomatis tersambung ke GitHub.</p>`);
const folder=path.join(out,'p',p.id);fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,'index.html'),html);
assert.ok(html.includes(p.id));assert.ok(html.includes('DATA DUMMY'));for(const v of Object.values(p.specs))assert.ok(html.includes(esc(v)));assert.ok(!html.includes('iris-product.jpg'));
}
fs.writeFileSync(path.join(out,'products-demo.json'),JSON.stringify(products,null,2));
console.log('Validated 10 distinct demo IDs, detail pages, metadata, specifications and replacement links.');

fs.cpSync(path.resolve(__dirname,'../assets/qr'),path.join(out,'qr'),{recursive:true});
fs.copyFileSync(path.resolve(__dirname,'../assets/qr-demo.zip'),path.join(out,'qr-demo.zip'));
